### HEALTH CHECK
GET http://localhost:5000/api/health

### REGISTER USER
POST http://localhost:5000/api/register
Content-Type: application/json

{
  "email": "test@sporex.com",
  "password": "123456",
  "username": "testuser",
  "name": "Test User"
}

### LOGIN USER
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "test@sporex.com",
    "password": "123456"
}


### CREATE READING (AUTHORIZED)
POST http://localhost:8000/api/readings
Content-Type: application/json
X-Device-Token: 6HGlMfWv9fV3ZhzGI6JxJlSFPXCbYaKwXsPzxPH7psxXR2GOfCrqp7UTj6SLcG3S

{
  "device_id": "sporex-esp32-01",
  "co2": 650,
  "temp_c": 24.3,
  "humidity": 55.2,
  "ts": 1700000000
}

### CREATE POST
POST http://localhost:5000/api/posts
Content-Type: application/json

{
  "user_name": "testuser",
  "post_name": "First Post",
  "content": "This is my first post about sustainable living!"
}

### LIST ALL POSTS
GET http://localhost:5000/api/posts

### GET SPECIFIC POST
GET http://localhost:5000/api/posts/69936b54ceeb4aa4e23a4967

### ADD REPLY TO POST
POST http://localhost:5000/api/posts/69936b54ceeb4aa4e23a4967/replies
Content-Type: application/json

{
  "user_name": "anotheruser",
  "content": "Great post! I totally agree with this approach."
}